export const postsData = [
  {
    userId: 1,
    id: 1,
    followers: 123,
    imageUrl: 'https://source.unsplash.com/random/300x300',
    name: 'Ajay Manikanta',
    workingAt: 'Techm',
    title:
      'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
    body: 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto',
  },
  {
    userId: 1,
    id: 2,
    followers: 890,
    imageUrl: 'https://source.unsplash.com/random/300x300',
    name: 'Vijay',
    workingAt: 'Infy',
    title: 'qui est esse',
    body: 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla',
  },
  {
    userId: 1,
    id: 3,
    followers: 767,
    imageUrl: 'https://source.unsplash.com/random/300x300',
    name: 'Mounica',
    workingAt: 'LTI',
    title: 'ea molestias quasi exercitationem repellat qui ipsa sit aut',
    body: 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut',
  },
  {
    userId: 1,
    id: 4,
    followers: 564,
    imageUrl: 'https://source.unsplash.com/random/300x300',
    name: 'Harshita',
    workingAt: 'Hashi corp',
    title: 'eum et est occaecati',
    body: 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit',
  },
  {
    userId: 1,
    id: 5,
    followers: 905,
    imageUrl: 'https://source.unsplash.com/random/300x300',
    name: 'Abdul',
    workingAt: 'Google',
    title: 'nesciunt quas odio',
    body: 'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque',
  },
  {
    userId: 1,
    id: 6,
    followers: 67,
    imageUrl: 'https://source.unsplash.com/random/300x300',
    name: 'Messi',
    workingAt: 'Wipro',
    title: 'dolorem eum magni eos aperiam quia',
    body: 'ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae',
  },
  {
    userId: 1,
    id: 7,
    followers: 237,
    imageUrl: 'https://source.unsplash.com/random/300x300',
    name: 'Sachin',
    workingAt: 'DMI',
    title: 'magnam facilis autem',
    body: 'dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas',
  },
  {
    userId: 1,
    id: 8,
    followers: 453,
    imageUrl: 'https://source.unsplash.com/random/300x300',
    name: 'Ram',
    workingAt: 'Wipro',
    title: 'dolorem dolore est ipsam',
    body: 'dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae',
  },
  {
    userId: 1,
    id: 9,
    followers: 34,
    imageUrl: 'https://source.unsplash.com/random/300x300',
    name: 'Nagaraju',
    workingAt: 'Movies (RRR)',
    title: 'nesciunt iure omnis dolorem tempora et accusantium',
    body: 'consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas',
  },
  {
    userId: 1,
    id: 10,
    followers: 90,
    imageUrl: 'https://source.unsplash.com/random/300x300',
    name: 'vishnu',
    workingAt: 'Krishna enterprises',
    title: 'optio molestias id quia eum',
    body: 'quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error',
  },
  {
    userId: 2,
    id: 11,
    followers: 666,
    imageUrl: 'https://source.unsplash.com/random/300x300',
    name: 'rohit',
    workingAt: 'Cognizant',
    title: 'et ea vero quia laudantium autem',
    body: 'delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi',
  },
];
